### ISSUE TITLE
Duplicate id

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/mffs-spring-2018#1]
Since you are using the same sidebar in 2 locations at the moment you are getting duplicate id attributes.

Try modifying the 'before_widget' code e.g. getting rid of the id

https://github.com/redacademy/mffs-spring-2018/blob/352bb2bdffae72b7f56051964e06b3517d88b1b3/themes/mffs-theme/functions.php#L62

**Comment by daniellino** [comment]
dear Jim,
thank you for the comments.
best
Daniel

**Comment by johnstonstu** [comment]
id removed from widget, because widget used in two locations
