### ISSUE TITLE
Remove console.log statements

### ISSUE THREAD

**Issue by rcass** [redacademy/mffs-spring-2018#10]
I looked at the plugin that you are using and it doesn't seem to have these console.log statements added, so I am guessing someone just added it for troubleshooting? 🤔 

Anyhow you should delete these lines:
https://github.com/redacademy/mffs-spring-2018/blob/3efd03343f74e2fabc3ff78ad4a5f3be239cc984/themes/mffs-theme/js/numscroller.js#L47-L48

**Comment by johnstonstu** [comment]
When console log removed, getting an 'unused variable' error from the num scroller js file.

**Comment by johnstonstu** [comment]
console log and unsued vars have been removed / fixed/
