### ISSUE TITLE
Rename widget area

### ISSUE THREAD

**Issue by rcass** [redacademy/mffs-spring-2018#11]
Since it seems this widget area is appearing in the footer I would rename it. The label `sidebar` is misleading. This can be changed in `functions.php`
![screen shot 2018-06-22 at 4 16 26 pm](https://user-images.githubusercontent.com/5028555/41802727-c28616ea-7637-11e8-95e8-dfadbe9c77c5.png)
_'hmm says sidebar but appears in the footer_' 🤔

**Comment by johnstonstu** [comment]
Sidebar widget renamed to Newsletter
