### ISSUE TITLE
function prefix names

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/mffs-spring-2018#2]
At the moment functions are still prefixed with the default red_starter
Please don't use find and replace to fix this as it could cause issues however you should try to update these prefixes to be mffs_

https://github.com/redacademy/mffs-spring-2018/blob/352bb2bdffae72b7f56051964e06b3517d88b1b3/themes/mffs-theme/functions.php#L14

**Comment by johnstonstu** [comment]
red_starter changed to mffs
