### ISSUE TITLE
Sanitize Output

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/mffs-spring-2018#3]
When getting field data e.g. CFS()->get you should sanitize the data with WordPress methods.

Some methods:
- esc_html()
- esc_url()
- esc_url_raw()
- wp_kses()
- wp_kses_post()

To use the methods, first check them out in the codex to understand what they are doing, try wrapping your fields with the methods e.g.

```<?php echo esc_url( CFS()->get( 'mffs_success_image_top') ); ?>```

https://github.com/redacademy/mffs-spring-2018/blob/352bb2bdffae72b7f56051964e06b3517d88b1b3/themes/mffs-theme/front-page.php#L29

**Comment by rcass** [comment]
If you need more resources about sanitizing data, here are the lesson slides about it [here](https://red-wdp.herokuapp.com/slides/wp-security-deployment-and-hosting-slides/#10)

Need even more resources 🤔 

- https://css-tricks.com/introduction-to-wordpress-front-end-security-escaping-the-things/
- https://premium.wpmudev.org/blog/ultimate-guide-wordpress-security/

**Comment by Showwtime** [comment]
Site has been sanitized
