### ISSUE TITLE
Update Readme files

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/mffs-spring-2018#5]
Not a huge issue but all the README.md files are currently the default RED Starter etc...

You should update the readme files to be relevant to the code you are writing.

**Comment by rcass** [comment]
I highly recommend adding screen shots since this is a WordPress theme and can't be hosted by a github page.

Other key things to think about are installation steps or developer notes. Think about *'what do I need to explain so another developer could understand this project and keep working'* 🤔

**Comment by Showwtime** [comment]
done and done
