### ISSUE TITLE
Fix page template

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/mffs-spring-2018#6]
I'm not sure why this was hardcoded the way it was but you should not create page templates this way.
Instead make sure you use the WordPress methods such as get_header get_footer etc...
Typically for page templates you can copy what's in index.php or page.php and then update the markup.

https://github.com/redacademy/mffs-spring-2018/blob/7264f40bb572f8755362d3adc032da59704ae0f7/themes/mffs-theme/page-newsletter.php#L8

**Comment by johnstonstu** [comment]
there is no header or footer on this page.
