### ISSUE TITLE
CFS Post id

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/mffs-spring-2018#7]
I'm not sure if you need the post id for these CFS fields, although if you do that's fine.
Try removing the id e.g. 15 and then see if you are still getting the info you need, otherwise you may be loading the fields for the wrong post.

https://github.com/redacademy/mffs-spring-2018/blob/7264f40bb572f8755362d3adc032da59704ae0f7/themes/mffs-theme/single-service.php#L31

**Comment by johnstonstu** [comment]
some of the post id's are required to get cfs data from other pages, some are not required...
